import type { ReactNode } from "react";
import { KeyboardAvoidingView, Platform, ScrollView, Text, TextInput, TouchableOpacity, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { colors, radius } from "../../src/themes/design";

export function AuthShell({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) {
  return <KeyboardAvoidingView style={{ flex: 1, backgroundColor: colors.background }} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ flexGrow: 1 }}><SafeAreaView style={{ flex: 1, paddingHorizontal: 22, paddingBottom: 28 }}><View style={{ alignItems: "center", paddingTop: 34, paddingBottom: 28 }}><View style={{ width: 58, height: 58, borderRadius: 18, backgroundColor: colors.primary, alignItems: "center", justifyContent: "center" }}><Ionicons name="people" size={28} color="#FFFFFF" /></View><Text style={{ color: colors.text, fontSize: 28, fontWeight: "900", marginTop: 17 }}>{title}</Text><Text style={{ color: colors.textMuted, fontSize: 14, lineHeight: 20, textAlign: "center", marginTop: 7 }}>{subtitle}</Text></View>{children}</SafeAreaView></ScrollView></KeyboardAvoidingView>;
}

type FieldProps = { label: string; value: string; onChangeText: (value: string) => void; placeholder: string; icon: keyof typeof Ionicons.glyphMap; error?: string; secure?: boolean; showSecure?: boolean; onToggleSecure?: () => void; keyboardType?: "default" | "email-address" | "phone-pad"; autoComplete?: any; returnKeyType?: "next" | "done" };
export function AuthField({ label, value, onChangeText, placeholder, icon, error, secure, showSecure, onToggleSecure, keyboardType = "default", autoComplete, returnKeyType }: FieldProps) {
  return <View style={{ marginBottom: 15 }}><Text style={{ color: colors.text, fontSize: 13, fontWeight: "800", marginBottom: 7 }}>{label}</Text><View style={{ height: 54, borderRadius: radius.medium, borderWidth: 1, borderColor: error ? colors.danger : colors.border, backgroundColor: colors.surface, flexDirection: "row", alignItems: "center", paddingHorizontal: 14 }}><Ionicons name={icon} size={19} color={error ? colors.danger : colors.textMuted} /><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#94A3B8" secureTextEntry={secure && !showSecure} keyboardType={keyboardType} autoCapitalize="none" autoCorrect={false} autoComplete={autoComplete} returnKeyType={returnKeyType} style={{ flex: 1, color: colors.text, fontSize: 15, marginLeft: 10, paddingVertical: 0 }} />{secure && <TouchableOpacity onPress={onToggleSecure} hitSlop={10}><Ionicons name={showSecure ? "eye-off-outline" : "eye-outline"} size={21} color={colors.textMuted} /></TouchableOpacity>}</View>{!!error && <Text style={{ color: colors.danger, fontSize: 11, marginTop: 5 }}>{error}</Text>}</View>;
}

export function AuthSegments({ value, onChange, options }: { value: string; onChange: (value: any) => void; options: { value: string; label: string; icon: keyof typeof Ionicons.glyphMap }[] }) {
  return <View style={{ flexDirection: "row", padding: 4, borderRadius: radius.medium, backgroundColor: "#E8EEF2", marginBottom: 20 }}>{options.map((option) => { const selected = option.value === value; return <TouchableOpacity key={option.value} onPress={() => onChange(option.value)} style={{ flex: 1, height: 42, borderRadius: 12, backgroundColor: selected ? colors.surface : "transparent", flexDirection: "row", alignItems: "center", justifyContent: "center" }}><Ionicons name={option.icon} size={17} color={selected ? colors.primary : colors.textMuted} /><Text style={{ color: selected ? colors.primary : colors.textMuted, fontWeight: "800", fontSize: 13, marginLeft: 6 }}>{option.label}</Text></TouchableOpacity>; })}</View>;
}

export function PrimaryAuthButton({ label, loading, disabled, onPress }: { label: string; loading?: boolean; disabled?: boolean; onPress: () => void }) {
  return <TouchableOpacity disabled={loading || disabled} onPress={onPress} activeOpacity={0.82} style={{ height: 54, borderRadius: radius.pill, backgroundColor: loading || disabled ? colors.disabled : colors.primary, flexDirection: "row", alignItems: "center", justifyContent: "center" }}>{loading && <Ionicons name="hourglass-outline" size={18} color="#FFFFFF" />}<Text style={{ color: "#FFFFFF", fontSize: 16, fontWeight: "900", marginLeft: loading ? 8 : 0 }}>{loading ? "Please wait…" : label}</Text></TouchableOpacity>;
}
